# Generated by Django 3.0.14 on 2024-04-15 06:48

import binance.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=100, verbose_name='SYMBOL')),
                ('orderId', models.CharField(max_length=100, verbose_name='ORDERID')),
                ('orderListId', models.CharField(max_length=100, verbose_name='ORDERLISTID')),
                ('clientOrderId', models.CharField(max_length=100, verbose_name='CLIENTORDERID')),
                ('price', models.CharField(max_length=100, verbose_name='PRICE')),
                ('origQty', models.CharField(max_length=100, verbose_name='ORIGQTY')),
                ('executedQty', models.CharField(max_length=100, verbose_name='EXECUTEDQTY')),
                ('cummulativeQuoteQty', models.CharField(max_length=100, verbose_name='CUMMULATIVEQUOTEQTY')),
                ('status', models.CharField(max_length=100, verbose_name='STATUS')),
                ('timeInForce', models.CharField(max_length=100, verbose_name='TIMEINFORCE')),
                ('type', models.CharField(max_length=100, verbose_name='TYPE')),
                ('side', models.CharField(max_length=100, verbose_name='SIDE')),
                ('stopPrice', models.CharField(max_length=100, verbose_name='STOPPRICE')),
                ('icebergQty', models.CharField(max_length=100, verbose_name='ICEBERGQTY')),
                ('time', models.CharField(max_length=100, verbose_name='TIME')),
                ('updateTime', models.CharField(max_length=100, verbose_name='UPDATETIME')),
                ('isWorking', models.CharField(max_length=100, verbose_name='ISWORKING')),
                ('origQuoteOrderQty', models.CharField(max_length=100, verbose_name='ORIGQUOTEORDERQTY')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', binance.models.EnField(max_length=100, verbose_name='API Key')),
                ('api_secret', binance.models.EnField(max_length=100, verbose_name='API Secret')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
